-- NOTHING PENDING. Emptied 2026-09-25 after Hidde pasted submissions.sign_photo;
-- confirmed against the live REST API the same minute.
--
-- When a new column or table is written, put its statement here as well, with
-- `if not exists`, so one paste in the SQL editor brings the database level.
-- `python3 scripts/sqlcheck.py` asks the live database what is still missing.
