-- NOTHING PENDING. Emptied 2026-09-24 after Hidde pasted the last batch
-- (sightings.girth_hugs, submissions.photo, sightings.sign_photo); all three
-- were confirmed against the live REST API the same hour.
--
-- When a new column or table is written, put its statement here as well, with
-- `if not exists`, so one paste in the SQL editor brings the database level.
-- `python3 scripts/sqlcheck.py` asks the live database what is still missing.
