-- THE TWO STATEMENTS THE LIVE DATABASE IS STILL MISSING, in one paste.
--
-- Generated by hand on 2026-09-23 after `python3 scripts/sqlcheck.py` found
-- that one of them had been waiting twelve days. Both are `if not exists`, so
-- running this twice does nothing the second time, and running it after
-- somebody has already pasted the original file does nothing at all.
--
-- Run `python3 scripts/sqlcheck.py` afterwards; it asks the live database
-- rather than taking anybody's word for it.

-- 1. HOW THICK THE TRUNK IS, as a reader answered it in the app: "<1", "1",
--    "2", "3" or "4+" adult hugs. From supabase/sightings.sql, written
--    2026-09-11 with the add-a-tree flow. Until this exists, the app asks the
--    question, posts the answer, and PostgREST drops it.
alter table public.sightings add column if not exists girth_hugs text;

-- 2. A PHOTOGRAPH ATTACHED TO A TIP from the website's form. From
--    supabase/submission-photos.sql, written 2026-09-23. The file itself goes
--    into the sightings bucket under the sender's own folder, which already
--    exists and needs nothing here; this is only where the path is recorded.
alter table public.submissions
  add column if not exists photo text
  check (photo is null or char_length(photo) <= 300);

-- 3. A SECOND PHOTOGRAPH, OF THE SIGN, when an old tree has one. Hidde's list,
--    2026-09-24: "vaak staat er een bordje bij een oude boom dus is het best
--    handig om naar een extra foto te vragen". A sign names the species, often
--    the age and the tree itself, so it settles "which trunk" and verifies in
--    one photograph. Optional in the flow; the file goes into the same bucket
--    and folder as the tree's photograph, so no storage policy changes.
alter table public.sightings
  add column if not exists sign_photo text
  check (sign_photo is null or char_length(sign_photo) <= 300);
