// Ported from the constants at the top of build_site.py (lines 55-90).
export const BASE_URL = "https://ancienttrees.app";

// The account track (Hidde, 2026-07-26): flipping this is his call, made in
// a session, never by a run. Flipped True 2026-07-30 once account deletion
// was verified end-to-end. build_site.py:68.
export const AUTH_ENABLED = true;

// Hidde's Supabase project (2026-07-28). The publishable key is public by
// design. build_site.py:70-71.
export const SUPABASE_URL = "https://caimvxiyrtifilimlkqw.supabase.co";
export const SUPABASE_KEY = "sb_publishable_qOTuw-LCejk2VhO2J6aXGQ_6X2O2mgb";

// Cloudflare Web Analytics: cookieless and aggregate only, chosen 2026-07-21
// specifically because it needs no consent banner. build_site.py:849.
export const ANALYTICS_TOKEN = "fcbbfb8b426c4f6aa2066b00be6454f6";

// The project identity, never the owner's name (Hidde, 2026-08-01).
// build_site.py:847.
export const CONTACT_EMAIL = "info@ancienttrees.app";

export const TITLE_MAX = 60;
export const DESC_MAX = 155;
// The floor a generated description should reach before it is allowed to stop
// on a sentence boundary. Google renders roughly 155 characters and that text
// is the entire click decision; anything much under 110 is both flagged by
// audit tools and, more to the point, leaves reason-to-go unread. 120 sits
// deliberately above that flag so a description clears it rather than grazing
// it. Only metaFromStory uses this: hand-written city and question copy is
// already comfortably long and is not padded to a number.
export const DESC_MIN = 120;

// build_site.py:85-88. Still plain <script>/<link> tags rather than the
// maplibre-gl npm package, so the island's behaviour stays byte-for-byte what
// Python shipped (worker loading, CSS, version) with no bundler-mediated
// difference. What changed on 2026-08-16 is the HOST: these are the same
// v4.7.1 files, vendored into site/public/assets and served from our own
// origin instead of unpkg.com.
//
// Three reasons, in the order they matter here. Privacy: unpkg saw the IP and
// user-agent of every visitor to every page with a map, which is most of the
// site, and the privacy page states we run no third-party tracking. Speed: a
// deferred script still needs its own DNS lookup and TLS handshake to a
// foreign host, while our own origin is already connected by the time the
// parser reaches this tag. Reliability: an unpkg outage took the maps out on
// every page, and the map is the product.
//
// Same bytes, so no behaviour changes; the smoke test asserts maps construct.
// Upgrading MapLibre now means re-fetching both files at the new version and
// renaming them here, which is deliberate: the version is visible in the
// filename rather than hidden in a URL nobody reads.
export const MAPLIBRE_JS = "/assets/maplibre-gl-4.7.1.js";
export const MAPLIBRE_CSS = "/assets/maplibre-gl-4.7.1.css";
// Our own style, generated by scripts/build_map_style.py from OpenFreeMap's
// positron and served from our own origin. Same tiles, same glyphs, same
// sprite, same attribution: a restyle rather than a new dependency.
//
// positron spends 20 layers on roads and 1 on parks, which for a site about
// trees standing in parks hides the content: on the stock style the Vondelpark
// is the same grey as the buildings around it. Regenerate with the script, do
// not hand-edit the JSON.
export const MAP_STYLE = "/assets/map-style.json";
