// The one slug rule, in a module with no Astro dependency so both users can
// import it. There were two copies until 2026-08-27: trees.ts for the pages
// and redirect-map.ts for the build integration, which runs before Astro's
// content collections exist and so could not import the first. Two copies of
// one rule is how a fix lands in one of them; that happened three separate
// times in a single day this week, so this one is shared.

/** Characters NFKD cannot decompose, which the ASCII fold below would delete
 * outright rather than fold.
 *
 * This is the bug the whole file exists to fix. Nordic a-ring and o-umlaut
 * survive an NFKD fold because it splits them into a letter plus a combining
 * mark, and the mark is what gets stripped. German sharp s has no
 * decomposition at all, so it was simply deleted: "Strasse" became "strae",
 * and 17 live URLs read like that, eleven of them in Munich. Icelandic eth
 * went the same way in Reykjavik.
 *
 * Polish l-stroke has no live victim yet and will get one the moment a
 * Wroclaw street name reaches a tree, which is why it is here now. */
const TRANSLIT: Record<string, string> = {
  "ß": "ss", // ß
  "ø": "o",  // ø
  "æ": "ae", // æ
  "œ": "oe", // œ
  "ł": "l",  // ł
  "đ": "d",  // đ
  "ð": "d",  // ð
  "þ": "th", // þ
  "ħ": "h",  // ħ
};

function fold(s: string): string {
  return s.replace(/[ßøæœłđðþħ]/g, (c) => TRANSLIT[c] ?? c);
}

/** The slug a tree or species name gets today. */
export function slugify(name: string): string {
  let s = name.toLowerCase().replace(/'/g, "").replace(/’/g, "");
  if (s.startsWith("the ")) s = s.slice(4);
  s = fold(s)
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^\x00-\x7F]/g, "");
  return s.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

/** The slug the same name got BEFORE the transliteration table existed.
 *
 * Frozen deliberately and forever. Google indexed these, so they have to keep
 * resolving under hard rule 3, and the redirect list is generated by asking
 * where this function and slugify() disagree rather than by anyone maintaining
 * a list of seventeen pairs by hand. Never "fix" this one. */
export function legacySlugify(name: string): string {
  let s = name.toLowerCase().replace(/'/g, "").replace(/’/g, "");
  if (s.startsWith("the ")) s = s.slice(4);
  s = s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^\x00-\x7F]/g, "");
  return s.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
