#!/usr/bin/env python3
"""Turn an export of linking domains into Google's disavow file. 2026-10-01.

Since 2026-07-24 roughly 300 domains of an SEO link network have linked to us
(itxoft-professional-seo-services.site, fiverr-seo-for-small-businesses.site,
rankgrowth.agency and the rest). Nobody bought them; these networks spray new
domains. Google says it ignores such links, so this is a cheap precaution
taken while the site is demoted, not the expected fix.

Usage:
  python3 scripts/disavow.py export.csv [more.csv ...]

Accepts Search Console's Links export ("Top linking sites") and Ahrefs'
referring-domains export: any CSV whose first column, or a column named like
"domain" / "site", holds a host. Writes drafts/disavow.txt, which Hidde uploads
at https://search.google.com/search-console/disavow-links (it needs his
account, hard rule 4).

What it never disavows: a domain in KEEP (links a person chose to make) or one
that is clearly a real institution. Anything else in the export is assumed to
be the network, because we have no other links; read the file before uploading.
"""
import csv
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEEP = {"getlisbon.com", "baumkunde.de", "ancienttrees.app", "google.com", "bing.com",
        "wikipedia.org", "wikimedia.org", "github.com", "apple.com", "chatgpt.com",
        "duckduckgo.com", "yahoo.com", "ecosia.org", "facebook.com", "reddit.com",
        "instagram.com", "x.com", "twitter.com", "linkedin.com", "youtube.com"}
REAL_TLD = re.compile(r"\.(gov|edu|ac\.[a-z]{2}|gov\.[a-z]{2})$")


def host_of(cell):
    cell = (cell or "").strip().lower()
    cell = re.sub(r"^https?://", "", cell).split("/")[0]
    return cell[4:] if cell.startswith("www.") else cell


def kept(h):
    return any(h == k or h.endswith("." + k) for k in KEEP) or bool(REAL_TLD.search(h))


def main(paths):
    if not paths:
        print(__doc__)
        return 1
    hosts = set()
    for p in paths:
        with open(p, newline="", encoding="utf-8-sig") as fh:
            rows = list(csv.reader(fh))
        if not rows:
            continue
        head = [c.lower() for c in rows[0]]
        col = next((i for i, c in enumerate(head) if "domain" in c or "site" in c or "host" in c), 0)
        for r in rows[1:]:
            if len(r) > col:
                h = host_of(r[col])
                if "." in h:
                    hosts.add(h)
    bad = sorted(h for h in hosts if not kept(h))
    good = sorted(h for h in hosts if kept(h))
    os.makedirs(os.path.join(ROOT, "drafts"), exist_ok=True)
    out = os.path.join(ROOT, "drafts", "disavow.txt")
    with open(out, "w") as fh:
        fh.write("# Ancient Trees disavow file, generated by scripts/disavow.py\n")
        fh.write("# The SEO link network that has linked to us since 2026-07-24.\n")
        for h in bad:
            fh.write("domain:%s\n" % h)
    print("%d domains to disavow, %d kept: %s" % (len(bad), len(good), ", ".join(good) or "-"))
    print("written to %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
